# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-03 01:15
from __future__ import unicode_literals

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='id',
        ),
        migrations.AddField(
            model_name='contact',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contact',
            name='messageList',
            field=django_mysql.models.ListCharField(models.CharField(max_length=1100), default=b'', max_length=3000, size=None),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False),
        ),
    ]
