# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-03 01:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_auto_20170903_0115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='messageList',
        ),
    ]
