# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-02 20:23
from __future__ import unicode_literals

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_auto_20170902_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='count',
            field=models.IntegerField(default=b'0'),
        ),
        migrations.AddField(
            model_name='contact',
            name='messageList',
            field=django_mysql.models.ListCharField(models.CharField(max_length=1100), default=b'', max_length=30, size=None),
        ),
    ]
