# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-03 01:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_remove_contact_messagelist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='count',
        ),
    ]
