# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-02 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_auto_20170902_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='count',
            field=models.IntegerField(),
        ),
    ]
